services:
    # Local development environment
    database:
        image: postgis/postgis:16-3.5-alpine
        container_name: spb_database
        restart: always
        ports:
            - 5432:5432
        environment:
            - POSTGRES_USER=spb_user
            - POSTGRES_PASSWORD=spb_password
            - POSTGRES_DB=spb_database
        volumes:
            - postgres_data:/var/lib/postgresql/data
        networks:
            - app-tier

    # Redis cache
    redis:
        image: redis:latest
        container_name: spb_redis
        restart: always
        command:
            [
                "redis-server",
                "/usr/local/etc/redis/redis.conf",
                "--bind",
                "redis",
            ]
        volumes:
            - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
            - redis_data:/data
        ports:
            - 6379:6379
        networks:
            - app-tier

networks:
    app-tier:
        driver: bridge

volumes:
    postgres_data:
    redis_data:
