services:

  # Local development environment
  database:
    image: postgres:16-alpine
    container_name: spb_database
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=spb_user
      - POSTGRES_PASSWORD=spb_password
      - POSTGRES_DB=spb_database
    volumes:
      - ./database:/var/lib/postgresql/data
    networks:
      - app-tier

  # Redis cache
  redis:
    image: bitnami/redis:latest
    container_name: spb_redis
    restart: always
    ports:
      - 6379:6379
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - app-tier

networks:
  app-tier:
    driver: bridge
