services:

  # Local development environment
  database:
    image: postgres:16-alpine
    container_name: spb_database
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=spb_user
      - POSTGRES_PASSWORD=spb_password
      - POSTGRES_DB=spb_database
    volumes:
      - $PWD/database:/var/lib/postgresql/data
    networks:
      - app-tier

  # Redis cache
  redis:
    image: redis:latest
    container_name: spb_redis
    restart: always
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - $PWD/redis/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - 6379:6379
    networks:
      - app-tier


networks:
  app-tier:
    driver: bridge
