package msg

// define message code to be used in the application
const (
	CODE_LOGIN_SUCCESS           = "MSGA001"
	CODE_REFRESH_TOKEN_SUCCESS   = "MSGA002"
	CODE_REGISTER_SUCCESS        = "MSGA003"
	CODE_VERIFY_TOKEN_SUCCESS    = "MSGA004"
	CODE_FORGOT_PASSWORD_SUCCESS = "MSGA005"
	CODE_RESET_PASSWORD_SUCCESS  = "MSGA006"

	CODE_CREATE_LOCATION_SUCCESS = "MSGL001"
	CODE_DELETE_LOCATION_SUCCESS = "MSGL002"
	CODE_GETALL_LOCATION_SUCCESS = "MSGL003"
	CODE_UPDATE_LOCATION_SUCCESS = "MSGL004"

	CODE_GET_METADATA_SUCCESS    = "MSGM001"
	CODE_UPDATE_METADATA_SUCCESS = "MSGM002"

	CODE_CREATE_UNIT_SUCCESS = "MSGU001"
	CODE_DELETE_UNIT_SUCCESS = "MSGU002"
	CODE_GET_UNIT_SUCCESS    = "MSGU003"
	CODE_UPDATE_UNIT_SUCCESS = "MSGU004"

	CODE_CREATE_UNIT_PRICE_SUCCESS = "MSGUP001"
	CODE_DELETE_UNIT_PRICE_SUCCESS = "MSGUP002"
	CODE_GET_UNIT_PRICE_SUCCESS    = "MSGUP003"
	CODE_UPDATE_UNITPRICE_SUCCESS  = "MSGUP004"

	CODE_CREATE_UNITSERVICE_SUCCESS = "MSGUS001"
	CODE_DELETE_UNITSERVICE_SUCCESS = "MSGUS002"
	CODE_GET_UNITSERVICE_SUCCESS    = "MSGUS003"
	CODE_UPDATE_UNITSERVICE_SUCCESS = "MSGUS004"

	CODE_CREATE_USER_SUCCESS = "MSGU001"
	CODE_DELETE_USER_SUCCESS = "MSGU002"
	CODE_GET_USER_SUCCESS    = "MSGU003"
	CODE_UPDATE_USER_SUCCESS = "MSGU004"
)
