.PHONY: clean critic security lint test build run dev gen

APP_NAME = spb_bsa
BUILD_DIR = $(PWD)/build
MIGRATIONS_DIR = $(PWD)/migrations

clean:
	rm -rf $(BUILD_DIR)

critic:
	gocritic check -enableAll ./...

security:
	gosec ./...

lint:
	golangci-lint run ./...

test: clean critic security lint
	go test -v -timeout 30s -coverprofile=cover.out -cover ./...
	go tool cover -func=cover.out

build: test
	CGO_ENABLED=0 go build -ldflags="-w -s" -o $(BUILD_DIR)/$(APP_NAME) ./main.go

run: build
	$(BUILD_DIR)/$(APP_NAME) start

dev: test
	go run $(PWD) start

gen: 
	go run $(PWD) generate --module_name $(MODULE)