projectName: "Sport booking"

server:
    env: local # local, prod
    host: "localhost"
    port: 7000

jwt:
    secret: "1234balhblahblah"

database:
    engine: "postgres"
    postgres:
        host: "localhost"
        port: "5432"
        user: "spb_user"
        pass: "spb_password"
        database: "spb_database"

logging:
    level: 0 # debug:0, info:1, warning:2, error:3
    type:
        - "zap" # log into logs/requests.log
    zap:
        output:
            - "console"
            - "file"
        filename: "requests.log"
    debugSymbol:

notification:
    smtp:
        host: "smtp.gmail.com"
        port: 587
        user: "xxxx@gmail.com"
        pass: "xxxxyyyyyzzzxz"

redis:
    host: "localhost"
    port: "6379"
