projectName: "Sport booking"

server:
    env: "development" # development, production
    host: "localhost"
    port: 7000

jwt:
    secret: "1234balhblahblah"
    accessTokenExp: 10
    refreshTokenExp: 43200

database:
    engine: "postgres"
    postgres:
        host: "localhost"
        port: "5432"
        user: "spb_user"
        password: "spb_password"
        dbname: "spb_database"
        sslMode: "disable"

redis:
    useCluster: false
    password: ""
    username: ""
    # user cluster
    clusterAddrs: ["localhost:6379"]
    # don't use cluster
    host: "127.0.0.1"
    port: 6379
    reset: false
    poolSize: 10
    db: 0

logging:
    level: 0 # debug:0, info:1, warning:2, error:3
    output:
        # - "console"
        - "file"
    filename: "requests.log"
    debugSymbol: "-"

notification:
    smtp:
        host: "smtp.gmail.com"
        port: 587
        user: "xxxx@gmail.com"
        pass: "xxxxyyyyyzzzxz"
