import LocalizedStrings from "react-native-localization";

const strings = new LocalizedStrings({
  en: {
    welcome: "Welcome to the app!",
    login: "Login",
    register: "Register",
    email: "Email",
    password: "Password",
    confirmPassword: "Confirm Password",
    forgotPassword: "Forgot Password?",
    continueWith: "Continue with",
    cancel: "Cancel",
    save: "Save",
    delete: "Delete",
    edit: "Edit",
    search: "Search",
    filter: "Filter",
    apply: "Apply",
    reset: "Reset",
    close: "Close",
    logout: "Logout",
    profile: "Profile",
    settings: "Settings",
    help: "Help",
    privacyPolicy: "Privacy Policy",
    termsOfService: "Terms of Service",
    language: "Language",
    theme: "Theme",
    
  },
  vi: {
    welcome: "Chào mừng đến với ứng dụng!",
    login: "Đăng nhập",
    register: "Đăng ký",
    email: "Email",
    password: "Mật khẩu",
    confirmPassword: "Xác nhận mật khẩu",
    forgotPassword: "Quên mật khẩu?",
    continueWith: "Tiếp tục với",
    cancel: "Hủy",
    save: "Lưu",
    delete: "Xóa",
    edit: "Sửa",
    search: "Tìm kiếm",
    filter: "Lọc",
    apply: "Áp dụng",
    reset: "Đặt lại",
    close: "Đóng",
    logout: "Đăng xuất",
    profile: "Hồ sơ",
    settings: "Cài đặt",
    help: "Trợ giúp",
    privacyPolicy: "Chính sách bảo mật",
    termsOfService: "Điều khoản dịch vụ",
    language: "Ngôn ngữ",
    theme: "Chủ đề",
  },
});
